### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by jpsweeney94** [sebastianpopp/discord-action#1]
Hello, I'm getting the following error when this action runs:
```
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
```

I assume i have something configured wrong since it's referring to local host?

Here is my discord job code:
```
discord:
    needs: changes
    if: ${{ needs.changes.outputs.hak == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: sebastianpopp/discord-action@releases/v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: Bla bla Bla
```

The other job it refers to runs successfully and the discord job executes, it just fails. 

`DISCORD_WEBHOOK` is a secret i have in the action settings of the repository, under "Repository secrets". That secret value matches the value of the secret field of my discord webhook in the "Webhooks" settings of the repo.

Am i configuring something wrong? Thanks
